services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dogtainers
      - POSTGRES_PASSWORD=dogtainers
    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql/data

    networks:
      - host

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@dogtainers.com.au
      - PGADMIN_DEFAULT_PASSWORD=user
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - host

volumes:
  db:
  pgadmin-data:

networks:
  host:
