services:
  postgresdb:
    image: postgres:14.1-alpine
    container_name: postgresDB_container
    restart: always
    environment:
      - postgresdb=dogtainers
      - POSTGRES_USER=dogtainers
      - POSTGRES_PASSWORD=dogtainers
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - host

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - postgresdb
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@dogtainers.com.au
      - PGADMIN_DEFAULT_PASSWORD=user
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - host

  web:
    image: 'nextapp'
    container_name: myApp_container
    build:
      context: '../audapp/'
      dockerfile: '../audapp/Dockerfile'
    volumes:
      - .:/var/www/nextapp
    ports:
     - 127.0.0.1:4000:3000
    depends_on:
     - "postgresdb"
    networks:
      - host
  
  # server:
  #   image: docker-server
  #   container_name: dotnetServer_container
  #   build:
  #     context: '../ExchangeRatesService'
  #     dockerfile: '../ExchangeRatesService/Dockerfile'
  #     target: final
  #   ports:
  #     - 5000:5151
  #   networks:
  #     - host

networks:
  host: